on:
  workflow_call:

jobs:
  docs-formatting:
    name: Validate docs formatting
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "v1.3.0"

      - name: Install dependencies
        working-directory: ./docs
        run: bun install --frozen-lockfile

      - name: Check formatting
        working-directory: ./docs
        run: bun format:check
